---
name: Build and Test

on: push  # yamllint disable-line rule:truthy
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Poetry
        run: |
          pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
          cache: poetry

      - name: Install dependencies with Poetry
        run: poetry install

      - name: Run pytest
        run: poetry run pytest
