---
name: Lint

on: push  # yamllint disable-line rule:truthy
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Markdownlint
        run: |
          npm install -g markdownlint-cli
          markdownlint -- $(git ls-files *.md)
