---
name: Lint

on: push  # yamllint disable-line rule:truthy
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Markdownlint action
        uses: xt0rted/markdownlint-problem-matcher@v1.1.0

      - name: Run Markdownlint
        run: markdownlint -- $(git ls-files *.md)
