---
name: Lint and Unit Test

on: push  # yamllint disable-line rule:truthy
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Poetry has to be installed before the setup-python action runs because
      # the setup-python cache looks for the poetry executable
      - name: Install Poetry
        run: |
          pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
          cache: poetry

      - name: Install pre-commit
        run: |
          pipx install pre-commit

      - name: Run Markdownlint
        run: |
          npm install -g markdownlint-cli
          markdownlint -- $(git ls-files *.md)

      - name: Install dependencies with Poetry
        run: poetry install

      - name: Run pre-commit on all files
        run: pre-commit run --all-files

      - name: Run unit tests with pytest
        run: poetry run pytest
